### ISSUE TITLE
Reading from process.stdin

### ISSUE THREAD

**Issue by jspears** [martinheidegger/simple-terminal-menu#1]
Thanks for the lib, really great.   I'm looking to create a cli version of [subschema](https://subschema.github.io/subschema), and this seems very promising.

So, not really an issue, but rather following the usual route spending several hours trying to figure it out, I thought maybe i'd ask.

How would one read text input from a user.   I tried just reading using the node-module read, but it screws up layout.   I figure anything I did without a lib would have same issue.   

Thanks!

**Comment by martinheidegger** [comment]
Hello @jspears,

Thank you for looking into this lib. There are imho. better cli tools for creating something like subschema. This menu has been reduced to one task. For your case maybe [inquirer](https://www.npmjs.com/package/inquirer) might be interesting?

But to answer your question: [readline2](https://www.npmjs.com/package/readline2) helps to create an interface.

**Comment by martinheidegger** [comment]
Closing issue,assuming it's clear to you
